package:
    name: extendpy
    version: 0.1.1

source:
  path: ..

requirements:
  build:
    - python
    - embedpy
    - pip

  host:
    - python
    - embedpy
    - pip
  run:
    - python
    - embedpy
    - pip
